### ISSUE TITLE
Node Modules are not usable inside clio

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#14]
This code:
```
import express from express/express

express -> call => app

fn handler req res:
    "hello world!" -> res.send

app -> get "/" handler
5000 -> app.listen
```
throws the following error:
```bash
ReferenceError: main is not defined
    at Object.clio_require (/home/garrit/dev/clio/internals/import.js:186:67)
    at module.exports (/home/garrit/dev/clio-express/.clio-cache/index.clio.js:3:20)
    at do_import (/home/garrit/dev/clio/internals/import.js:357:29)
    at clio_import (/home/garrit/dev/clio/internals/import.js:395:10)
    at process_file (/home/garrit/dev/clio/index.js:40:12)
    at Object.require.command.argv [as handler] (/home/garrit/dev/clio/index.js:110:7)
    at Object.runCommand (/home/garrit/dev/clio/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/home/garrit/dev/clio/node_modules/yargs/yargs.js:1078:30)
    at Object.get [as argv] (/home/garrit/dev/clio/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/home/garrit/dev/clio/index.js:222:16)
```

I believe it has something to do with the node modules, as i get the same issue when trying to import lodash

**Comment by pouya-eghbali** [comment]
One of the strings wasn't wrapped in `"`, we can import a directory if there's a `main.clio` file in it (it's inspired by Python's `__init__.py` files).
