### ISSUE TITLE
@eager position emits error when not above function declaration

### ISSUE THREAD

**Issue by Tapmemer** [clio-lang/clio#18]
putting @eager next to fn i.e:
`@eager fn greet name:
  'hello' name -> print`

causes the following error
`TypeError: analyzers[node.name] is not a function
    at /usr/lib/node_modules/clio-lang/evaluator/analyzer.js:874:42
    at Array.map (<anonymous>)
    at analyze (/usr/lib/node_modules/clio-lang/evaluator/analyzer.js:873:25)
    at analyzer (/usr/lib/node_modules/clio-lang/evaluator/analyzer.js:885:10)
    at do_import (/usr/lib/node_modules/clio-lang/internals/import.js:341:23)
    at clio_import (/usr/lib/node_modules/clio-lang/internals/import.js:395:10)
    at process_file (/usr/lib/node_modules/clio-lang/index.js:40:12)
    at Object.require.command.argv [as handler] (/usr/lib/node_modules/clio-lang/index.js:110:7)
    at Object.runCommand (/usr/lib/node_modules/clio-lang/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/usr/lib/node_modules/clio-lang/node_modules/yargs/yargs.js:1078:30)`

**Comment by pouya-eghbali** [comment]
Hello. This is by design. `eager` is a function and `@` here is the decorator symbol. Decorators are functions that get a function as argument (and probably some extra arguments too) and return another function. In this case, `eager` takes a lazy function and returns an eager one. Clio decorators are similar to Python decorators. `@eager` isn't a special keyword and shouldn't be used behind an `fn` keyword.

The decorator syntax is:

```
@decorator_function arg1 arg2 arg3
fn fn_name fn_arg:
  -- function body
```

and for inline mode (in flow, for anonymous functions):

```
data -> (@decorator_fn arg1 arg2) fn n:
  -- function body
```
